//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRolando.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensePayments
    {
        public long Id { get; set; }
        public decimal Amount { get; set; }
        public decimal ExchangeRate { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Comment { get; set; }
        public long ExpenseInvoiceID { get; set; }
    
        public virtual ExpenseInvoices ExpenseInvoices { get; set; }
    }
}
