//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRolando.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseInvoices()
        {
            this.ExpensePayments = new HashSet<ExpensePayments>();
        }
    
        public long Id { get; set; }
        public string Concept { get; set; }
        public decimal ExchangeRate { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Total { get; set; }
        public decimal Pending { get; set; }
        public string AdditionalNotes { get; set; }
        public long ProviderId { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensePayments> ExpensePayments { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
