//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRolando.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AxosnetTestEntities : DbContext
    {
        public AxosnetTestEntities()
            : base("name=AxosnetTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExpenseInvoices> ExpenseInvoices { get; set; }
        public virtual DbSet<ExpensePayments> ExpensePayments { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
    }
}
